//! Private opt-in instrumentation. Fields contain syntax metadata and outcome
//! classifications only; values, evaluated paths and error text are never read.

use std::cell::Cell;
use std::fmt;
use std::io::Write;
use std::sync::atomic::{AtomicU64, Ordering};

use crate::error::Result;
use crate::model::{Value, ValueCow, ValueView};
use crate::parser::Filter;
use crate::runtime::{Renderable, Runtime};

static NEXT_BUFFER: AtomicU64 = AtomicU64::new(1);
thread_local! {
    static PARSE_BUFFER: Cell<u64> = const { Cell::new(0) };
}

/// Coordinates identify a parser input buffer, including buffers generated by
/// plugins. They are not implicitly coordinates in an external template file.
#[derive(Clone, Copy)]
pub(crate) struct Position {
    buffer_id: u64,
    line: usize,
    column: usize,
    byte: usize,
}

impl Position {
    pub(crate) fn new(position: pest::Position<'_>) -> Self {
        let (line, column) = position.line_col();
        Self {
            buffer_id: PARSE_BUFFER.with(Cell::get),
            line,
            column,
            byte: position.pos(),
        }
    }

    pub(crate) fn enter(self) -> ParseBufferGuard {
        ParseBufferGuard::enter(self.buffer_id)
    }
}

pub(crate) struct ParseBufferGuard(u64);
impl ParseBufferGuard {
    pub(crate) fn new() -> Self {
        Self::enter(NEXT_BUFFER.fetch_add(1, Ordering::Relaxed))
    }
    fn enter(id: u64) -> Self {
        Self(PARSE_BUFFER.with(|current| current.replace(id)))
    }
}
impl Drop for ParseBufferGuard {
    fn drop(&mut self) {
        PARSE_BUFFER.with(|current| current.set(self.0));
    }
}

pub(crate) struct ProfiledRenderable {
    inner: Box<dyn Renderable>,
    position: Position,
    kind: &'static str,
    name: Option<String>,
}
impl ProfiledRenderable {
    pub(crate) fn wrap(
        inner: Box<dyn Renderable>,
        position: Position,
        kind: &'static str,
        name: Option<&str>,
    ) -> Box<dyn Renderable> {
        Box::new(Self {
            inner,
            position,
            kind,
            name: name.map(str::to_owned),
        })
    }
}
impl fmt::Debug for ProfiledRenderable {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.inner.fmt(f)
    }
}
impl Renderable for ProfiledRenderable {
    fn is_blank(&self) -> bool {
        self.inner.is_blank()
    }
    fn trim_blank(&mut self) {
        self.inner.trim_blank();
    }
    fn render_to(&self, writer: &mut dyn Write, runtime: &dyn Runtime) -> Result<()> {
        let p = self.position;
        let span = tracing::trace_span!(target: "liquid::profile::node", "liquid.node",
            kind = self.kind, name = tracing::field::Empty,
            buffer_id = p.buffer_id, line = p.line, column = p.column,
            byte = p.byte, ok = tracing::field::Empty);
        if let Some(name) = self.name.as_deref() {
            span.record("name", name);
        }
        let _entered = span.enter();
        let result = self.inner.render_to(writer, runtime);
        span.record("ok", result.is_ok());
        result
    }
}

pub(crate) struct ProfiledFilter {
    inner: Box<dyn Filter>,
    position: Position,
    name: String,
}
impl ProfiledFilter {
    pub(crate) fn wrap(inner: Box<dyn Filter>, position: Position, name: &str) -> Box<dyn Filter> {
        Box::new(Self {
            inner,
            position,
            name: name.to_owned(),
        })
    }
}
impl fmt::Debug for ProfiledFilter {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Debug::fmt(&self.inner, f)
    }
}
impl fmt::Display for ProfiledFilter {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Display::fmt(&self.inner, f)
    }
}
impl Filter for ProfiledFilter {
    fn evaluate(&self, input: &dyn ValueView, runtime: &dyn Runtime) -> Result<Value> {
        let p = self.position;
        let span = tracing::trace_span!(target: "liquid::profile::filter", "liquid.filter",
            name = self.name.as_str(), buffer_id = p.buffer_id,
            line = p.line, column = p.column, byte = p.byte,
            ok = tracing::field::Empty);
        let _entered = span.enter();
        let result = self.inner.evaluate(input, runtime);
        span.record("ok", result.is_ok());
        result
    }
}

fn record_value(span: &tracing::Span, value: Option<&ValueCow<'_>>) {
    span.record("found", value.is_some());
    if let Some(value) = value {
        span.record("owned", matches!(value, ValueCow::Owned(_)));
    }
}

pub(crate) fn lookup_try<'a>(
    mode: &'static str,
    depth: usize,
    operation: impl FnOnce() -> Option<ValueCow<'a>>,
) -> Option<ValueCow<'a>> {
    let span = tracing::trace_span!(target: "liquid::profile::lookup", "liquid.lookup",
        mode, depth, found = tracing::field::Empty, owned = tracing::field::Empty);
    let _entered = span.enter();
    let result = operation();
    record_value(&span, result.as_ref());
    result
}

pub(crate) fn lookup_get<'a>(
    depth: usize,
    operation: impl FnOnce() -> Result<ValueCow<'a>>,
) -> Result<ValueCow<'a>> {
    let span = tracing::trace_span!(target: "liquid::profile::lookup", "liquid.lookup",
        mode = "strict", depth, found = tracing::field::Empty,
        owned = tracing::field::Empty, ok = tracing::field::Empty);
    let _entered = span.enter();
    let result = operation();
    span.record("ok", result.is_ok());
    record_value(&span, result.as_ref().ok());
    result
}

pub(crate) fn project<'a>(operation: impl FnOnce() -> ValueCow<'a>) -> ValueCow<'a> {
    let span = tracing::trace_span!(target: "liquid::profile::project", "liquid.project",
        owned = tracing::field::Empty);
    let _entered = span.enter();
    let result = operation();
    span.record("owned", matches!(result, ValueCow::Owned(_)));
    result
}

pub(crate) fn frame_try<'a>(
    frame: &'static str,
    depth: usize,
    operation: impl FnOnce(&tracing::Span) -> Option<ValueCow<'a>>,
) -> Option<ValueCow<'a>> {
    let span = tracing::trace_span!(target: "liquid::profile::frame", "liquid.frame",
        frame, mode = "try", depth, delegated = false,
        found = tracing::field::Empty, owned = tracing::field::Empty);
    let _entered = span.enter();
    let result = operation(&span);
    record_value(&span, result.as_ref());
    result
}

pub(crate) fn frame_get<'a>(
    frame: &'static str,
    depth: usize,
    operation: impl FnOnce(&tracing::Span) -> Result<ValueCow<'a>>,
) -> Result<ValueCow<'a>> {
    let span = tracing::trace_span!(target: "liquid::profile::frame", "liquid.frame",
        frame, mode = "strict", depth, delegated = false,
        found = tracing::field::Empty, owned = tracing::field::Empty,
        ok = tracing::field::Empty);
    let _entered = span.enter();
    let result = operation(&span);
    span.record("ok", result.is_ok());
    record_value(&span, result.as_ref().ok());
    result
}
